name: Build & deploy docs to GitHub pages

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build the Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          environments: dev
      - name: Build docs
        run: pixi run -e dev docs
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/

  deploy:
    name: Deploy the docs to GitHub pages
    permissions:
      pages: write       # Added for GitHub Pages deployment
      id-token: write    # Necessary for actions/deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
